commerce_solving_maze.settings:
  type: config_object
  label: 'Solving Maze settings'
  mapping:
    api_key:
      type: string
      label: 'API key'
    warehouse_id:
      type: string
      label: 'Warehouse id'
